@OrderSystem_HostAddress = http://localhost:5208

### Create Product
POST {{OrderSystem_HostAddress}}/Products
Content-Type: application/json

{
  "name": "Gaming Laptop",
  "price": 1899.99,
  "stockQuantity": 1
}

### Get all Products
GET {{OrderSystem_HostAddress}}/Products

### Get Product by Id
GET {{OrderSystem_HostAddress}}/Products/7

### Update Product
PUT {{OrderSystem_HostAddress}}/Products/7
Content-Type: application/json

{
  "name": "Laptop v2",
  "price": 1299.00,
  "stockQuantity": 7
}

### Create Customer
POST {{OrderSystem_HostAddress}}/Customers
Content-Type: application/json

{
  "firstName": "Abdullah",
  "lastName": "Sherif",
  "customerType": "Employee"
}

### Get all Customers
GET {{OrderSystem_HostAddress}}/Customers

### Get Customer by Id
GET {{OrderSystem_HostAddress}}/Customers/4

### Update Customer
PUT {{OrderSystem_HostAddress}}/Customers/4
Content-Type: application/json

{
  "firstName": "Abdullah",
  "lastName": "Sayed",
  "customerType": "WholeSale"
}

### Create Order
POST {{OrderSystem_HostAddress}}/Orders
Content-Type: application/json

{
  "customerId": 4,
  "items": [
    { "productId": 5, "qty": 2 },
    { "productId": 2, "qty": 3 },
    { "productId": 3, "qty": 1 }
  ]
}

### Get all Orders
GET {{OrderSystem_HostAddress}}/Orders

### Get Order by Id
GET {{OrderSystem_HostAddress}}/Orders/4

### Update Order Status
PATCH {{OrderSystem_HostAddress}}/Orders/3/status
Content-Type: application/json

{
  "orderStatus": "New"
}

### Delete Order
DELETE {{OrderSystem_HostAddress}}/Orders/5

### Delete Product
DELETE {{OrderSystem_HostAddress}}/Products/10

### Delete Customer
DELETE {{OrderSystem_HostAddress}}/Customers/4