using Microsoft.AspNetCore.Identity;
using OrderSystem.Application.DTOs.Auth;
using OrderSystem.Application.Interfaces.Repositories;
using OrderSystem.Application.Interfaces.Services;
using OrderSystem.Domain.Entities;

namespace OrderSystem.Infrastructure.Services
{
    public class AuthService : IAuthService
    {
        private readonly IUserRepository _userRepository;
        private readonly IRefreshTokenRepository _refreshTokenRepository;
        private readonly IUnitOfWork _uow;
        private readonly ITokenService _tokenService;
        private readonly PasswordHasher<User> _passwordHasher = new PasswordHasher<User>();

        public AuthService(IUserRepository userRepository, IRefreshTokenRepository refreshTokenRepository, IUnitOfWork uow, ITokenService tokenService)
        {
            _userRepository = userRepository;
            _refreshTokenRepository = refreshTokenRepository;
            _uow = uow;
            _tokenService = tokenService;
        }

        public async Task<AuthResponse> RegisterAsync(RegisterRequest request)
        {
            // Check for existing username/email
            if (await _userRepository.UsernameExistsAsync(request.Username))
                throw new InvalidOperationException("Username already exists.");

            if (await _userRepository.EmailExistsAsync(request.Email))
                throw new InvalidOperationException("Email already exists.");

            // Create new user
            var user = new User
            {
                Username = request.Username,
                Email = request.Email,
                PasswordHash = "",
            };
            // Hash password
            user.PasswordHash = _passwordHasher.HashPassword(user, request.Password);

            await _userRepository.CreateAsync(user);
            await _uow.CommitAsync(); // Commit first so user.Id is generated by the DB

            var response = await IssueTokensAsync(user, null);
            await _uow.CommitAsync(); // Commit the refresh token
            
            return response;
        }

        public async Task<AuthResponse> LoginAsync(LoginRequest request)
        {
            // Find user
            var user = await _userRepository.GetByUsernameAsync(request.Username);
            if (user is null)
                throw new UnauthorizedAccessException("Invalid username or password.");

            // Verify password
            var result = _passwordHasher.VerifyHashedPassword(user, user.PasswordHash, request.Password);
            if (result == PasswordVerificationResult.Failed)
                throw new UnauthorizedAccessException("Invalid username or password.");

            var response = await IssueTokensAsync(user, request.DeviceInfo);
            await _uow.CommitAsync();

            return response;
        }

        public async Task<AuthResponse> RefreshTokenAsync(RefreshTokenRequest request)
        {
            var hashedToken = _tokenService.HashToken(request.RefreshToken);
            var storedToken = await _refreshTokenRepository.GetByTokenAsync(hashedToken);
            if (storedToken is null || !storedToken.IsActive)
                throw new UnauthorizedAccessException("Invalid or expired refresh token.");

            // Revoke old refresh token
            storedToken.RevokedAt = DateTime.UtcNow;

            var response = await IssueTokensAsync(storedToken.User, storedToken.DeviceInfo);
            await _uow.CommitAsync();

            return response;
        }

        public async Task RevokeTokenAsync(string refreshToken)
        {
            var hashedToken = _tokenService.HashToken(refreshToken);
            var storedToken = await _refreshTokenRepository.GetByTokenAsync(hashedToken);
            if (storedToken is null || !storedToken.IsActive)
                throw new InvalidOperationException("Token not found or already inactive.");

            storedToken.RevokedAt = DateTime.UtcNow;
            await _uow.CommitAsync();
        }

        private async Task<AuthResponse> IssueTokensAsync(User user, string? deviceInfo)
        {
            var accessToken = _tokenService.GenerateAccessToken(user);
            var refreshTokenString = _tokenService.GenerateRefreshToken();
            
            var refreshToken = new RefreshToken
            {
                TokenHash = _tokenService.HashToken(refreshTokenString),
                UserId = user.Id,
                DeviceInfo = deviceInfo,
                ExpiresAt = _tokenService.GetRefreshTokenExpiry(),
                CreatedAt = DateTime.UtcNow
            };

            await _refreshTokenRepository.CreateAsync(refreshToken);

            return new AuthResponse
            {
                AccessToken = accessToken,
                RefreshToken = refreshTokenString,
                AccessTokenExpiresAt = _tokenService.GetAccessTokenExpiry()
            };
        }
    }
}
